services:
  - type: web
    name: referal-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cd referal_app
      python3 manage.py makemigrations
      python3 manage.py migrate
      python3 manage.py collectstatic --noinput
    startCommand: |
      cd referal_app
      gunicorn referal_app.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: referal_app.settings
      - key: SECRET_KEY
        sync: false
    plan: free
databases:
  - name: hs-db
    plan: free
    
      