services:
  - type: web
    name: referal-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn referal_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: referal_app.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: referal-app-db
          property: connectionString
    databases:
      - name: referal-app-db
        plan: free
        postgresVersion: 13