services:
  - type: web
    name: referal-app
    env: python
    plan: free
    buildCommand: "poetry install"
    startCommand: "poetry run gunicorn referal_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: referal_app.settings
      - key: SECRET_KEY
        sync: false