services:
  - type: web
    name: referal-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cd referral_app && python3 manage.py makemigrations && python3 manage.py migrate"
    startCommand: "cd referal_app && gunicorn referal_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: referal_app.settings
      - key: SECRET_KEY
        sync: false
      